name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  

    steps:
      - uses: actions/checkout@v2
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
      - name: run
        run: mingw32-make
